spring:
  profiles:
    active: datasource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#logging:
#  level:
#    com.baomidou.mybatisplus.samples.quickstart: debug